### ISSUE TITLE
"Unsupported" Standard Logic Types

### ISSUE THREAD

**Issue by C47D** [tgingold/ghdlsynth-beta#13]
Doing other little project i find out that some standard types have no support yet, the types that give me the following error 

> ERROR: Unsupported(1): instance \types%1 of $const_UL32.

 are:

- '-' (don't care)
- 'U' (undefined)
- 'X' (unknown strong value)
- 'Z' (high impedance)
- 'H' (weak 1)

I had not seen U, X and H used on the book i am reading but i guess Z and - are used more.

Thanks in advance
Carlos

[test.zip](https://github.com/tgingold/ghdlsynth-beta/files/811772/test.zip)

**Comment by tgingold** [comment]
On 01/03/17 20:07, Carlos Diaz wrote:
> Doing other little project i find out that some standard types have no
> support yet, the types that give me the following error
>
>     ERROR: Unsupported(1): instance \types%1 of $const_UL32.
>
> are:
>
>   * '-' (don't care)
>   * 'U' (undefined)
>   * 'X' (unknown strong value)
>   * 'Z' (high impedance)
>   * 'H' (weak 1)
>
> I had not seen U, X and H used on the book i am reading but i guess Z
> and - are used more.

Yes, none of them are currently supported.  Enhancement request.

Tristan.

**Comment by tgingold** [comment]
I think this is now fixed by pr #28

**Comment by C47D** [comment]
Thanks @tgingold, it has been a while since the issue was opened, i have no access to my fpga at the moment, but i will close this issue and re-open it in case of any trouble. Thanks for your work :)
