### ISSUE TITLE
Cannot find gnat-7 in apt-get

### ISSUE THREAD

**Issue by RCoeurjoly** [tgingold/ghdlsynth-beta#20]
There is now not such package as gnat-7 in apt-get repositories.

All we can get is gnat-5 or gnat-4.9

I tried to install the gnat-7 package from other ways (architecture specific, .deb package from Debian), but I think it is not the most appropriate way because I am still unsuccessful in building the project and it is architecture specific. Also, the [website ](https://packages.debian.org/buster/gnat-7) suggests:

> If you are running Debian, it is strongly suggested to use a package manager like aptitude or synaptic to download and install packages, instead of doing so manually via this website.

Correct me if I am wrong, but [GNAT is part of GCC](https://gcc.gnu.org/wiki/GNAT).
What features of gnat-7 do we need that are not part of the package gnat?

**Comment by tgingold** [comment]
Maybe the package gnat would work.  ghdl-synth is using more recent features than ghdl; but this
will quickly be detected at compile time.  So try with gnat-5 or even gnat-4.9
